### ISSUE TITLE
The application cannot be used

### ISSUE THREAD

**Issue by MrAlexanderWs** [ahmadbagwi/sertifikat-online#2]
Hey @ahmadbagwi there is an error in this. Databse has no ID column. 
![error 123](https://user-images.githubusercontent.com/46021397/108489428-1f60c180-72d4-11eb-8b47-12e7bb71e9e7.png)

Changing to mysql to mysqli still not fixed yet!
![29](https://user-images.githubusercontent.com/46021397/108489553-428b7100-72d4-11eb-8e4c-fbb5c0c3dcdd.png)

Database has no id 
![cannot](https://user-images.githubusercontent.com/46021397/108489719-78305a00-72d4-11eb-8ec4-3385294bba32.png)

This needs to be fixed yet!

**Comment by ahmadbagwi** [comment]
Hi, I just update mysqli & php, please check. Database only sample, you free to modify according to the needs
